### ISSUE TITLE
m3u8文件中包含多条清晰度，只能拉起最低清晰度的ts？

### ISSUE THREAD

**Issue by 1265578519** [MoePlayer/DPlayer#494] opened 2019-06-14 22:53 UTC
例如url:
http://7xlv47.com1.z0.glb.clouddn.com/xxx004.m3u8

#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=200000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/0
#EXT-X-STREAM-INF:BANDWIDTH=800000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/1
#EXT-X-STREAM-INF:BANDWIDTH=1700000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/2
#EXT-X-STREAM-INF:BANDWIDTH=2400000
/Jh8rYx351Yrg7hBKrIKNdclqxLs=/lv1f9Ik9kERn5N3rjg2jVbH_nrF5/3

**Comment by 1265578519** [comment] 2019-06-14 22:53
之前看到有人提过，不过这么久了还没人增加
https://github.com/MoePlayer/DPlayer/issues/291

**Comment by kt286** [comment] 2019-08-29 08:47
貌似是根据网络状况自动切换清晰度的
![image](https://user-images.githubusercontent.com/10684972/63922658-ab937f00-ca77-11e9-90db-d0fe92e7545f.png)

**Comment by DIYgod** [comment] 2019-09-27 08:54
Duplicate of #291

**Closed by DIYgod** 2019-09-27 08:54 UTC
